### ISSUE TITLE
automatic rotation 

### ISSUE THREAD

**Issue by melsss** [Echsecutor/Echsecutable-Memory#4]
If I turn my phone the app stops working.
The application should either turn as well or stay fixed, instead the screen goes black.

**Comment by Echsecutor** [comment]
Danke!
Das liegt denke ich daran, dass die Bilder beim drehen neu geladen werden, das überfordert evtl Deinen Arbeitsspeicher....
Ich arbeite dran.

**Comment by Echsecutor** [comment]
Nein, es lag daran, dass Dein Telephon zu alt ist. ;)

Anyway: fixed.
