### ISSUE TITLE
resolution of images

### ISSUE THREAD

**Issue by pat1986** [Echsecutor/Echsecutable-Memory#5]
the resolution of the images is too low so that it doesn´t look good

**Comment by Echsecutor** [comment]
Danke!
Ich habe die Bilder alle in hoher Auflösung, hatte die aber absichtlich runterskaliert bis auf die größe die auch in etwa angezeigt wird. Ich werde mal schauen, dass ich da noch mehrere Sets in passenden Auflösungen, je nach device, produziere.

**Comment by Echsecutor** [comment]
added various versions of the images in different resolutions
